### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by louisyssel** [BearWare/TeamTalk5Setup#1]
Do you perhaps have decent installation instructions for TeamTalk5 Server on Centos 7. I am unable to find any decent explanations or instructions anywhere. From what I am able to see, this is what I require, but I am unable to get the server setup running on Centos 7.

Your help will be appreciated.

Louis

**Comment by louisyssel** [comment]
I have tried to do as much as I can, but without any proper documentation, it is no use.

I installed it, and I am able to successfully start the tt5 server, but this is what I get when I connect to the server from a browser.
<img width="826" alt="image" src="https://user-images.githubusercontent.com/29566427/43250909-becc009a-90be-11e8-8c36-273a97395810.png">

I assume there is some prerequisite I am missing.

Please assist!!

**Comment by louisyssel** [comment]
OK, I seem to have resolved the issue, I am not supposed to connect to the server using a browser. I am now able to connect to the server with a TeamTalk5 client. Will test further.

**Comment by bear101** [comment]
Why do you connect a web browser to a TeamTalk server?

**Comment by louisyssel** [comment]
Because I assumed that as TeamTalk5 is a "WebRTC" type solution, It would be accessible through the browser.

**Comment by bear101** [comment]
Assumptions is the mother of all... :-)

**Comment by louisyssel** [comment]
Not entirely in agreement here. You should really look at the state of your documentation. All products out there today caters for browser communications, and you do not state the contrary anywhere, most certainly your documentation does not even state the basics such as:

1. Start the server using "su -c "/home/tt/tt5/tt5srv -d" ttsu -c"
2. Once started successfully, start the client, and select the Connect Box, and input the server information.

But there is nothing.
